ARG PG_MANAGED_IMAGE_REF
FROM docker.io/${PG_MANAGED_IMAGE_REF} AS build

# Dir for environment source files (eg src-env/<whatever>), if any
ARG PG_MANAGED_SRC_ENV_DIR

# Password for app_exec USER, that only has accesss to call procedures and functions
ARG PG_MANAGED_EXEC_PASS

# Number of seed customers to generate
ARG PG_MANAGED_NUM_SEED_CUSTOMERS

# Copy all sql scripts
COPY src/* /docker-entrypoint-initdb.d

# Copy all sql scripts
#COPY ${PG_MANAGED_SRC_ENV_DIR}/* /docker-entrypoint-initdb.d

# Replace every occurrence of variables in copied sql scripts with value of build arg
# - PG_MANAGED_EXEC_PASS         : the password for the managed_app_exec role that the app will login as
# - PG_MANAGED_NUM_SEED_CUSTOMERS: the number of seed customers to generate
#
# Note that in the sed command, the text to search for have the opening ${ and closing } enclosed in square brackets, so
# that they are literal sequences to search for.
RUN find /docker-entrypoint-initdb.d -type f -name '*.sql' -exec sed -i 's,[$][{]PG_MANAGED_EXEC_PASS[}],'${PG_MANAGED_EXEC_PASS}',;s,[$][{]PG_MANAGED_NUM_SEED_CUSTOMERS[}],'${PG_MANAGED_NUM_SEED_CUSTOMERS}',' '{}' \;
