ARG PG_MANAGED_IMAGE_REF
FROM docker.io/${PG_MANAGED_IMAGE_REF} AS build

# Password for app_exec USER, that only has accesss to call procedures and functions
ARG PG_MANAGED_EXEC_PASS

# Number of seed customers to generate
ARG PG_MANAGED_NUM_SEED_CUSTOMERS

# Dir for environment source files
ARG PG_SRC_ENV_DIR=

# Copy all sql scripts
COPY src/* /docker-entrypoint-initdb.d

# Copy environment specific files, if any
#COPY ${PG_SRC_ENV_DIR}/* /docker-entrypoint-initdb.d

# Replace every occurrence of variables in copied sql scripts with value of build arg
# - PG_MANAGED_EXEC_PASS         : the password for the managed_app_exec role that the app will login as
# - PG_MANAGED_NUM_SEED_CUSTOMERS: the number of seed customers to generate
#
# Note that in the sed command, the text to search for must have the opening ${ and closing } enclosed in square
# brackets, so that they are literal sequences to search for.
RUN find /docker-entrypoint-initdb.d -type f -name '*.sql' -exec sed -i 's,[$][{]PG_MANAGED_EXEC_PASS[}],'${PG_MANAGED_EXEC_PASS}',g' '{}' \;
RUN find /docker-entrypoint-initdb.d -type f -name '*.sql' -exec sed -i 's,[$][{]PG_MANAGED_NUM_SEED_CUSTOMERS[}],'${PG_MANAGED_NUM_SEED_CUSTOMERS}',g' '{}' \;
